#
# Module manifest for module 'WindowsDisplayManager'
#
# Generated by: Patrick Fieldson
#
# Generated on: 11/8/2023
#

@{
# Script module or binary module file associated with this manifest.
RootModule = 'WindowsDisplayManager.psm1'

# Version number of this module.
ModuleVersion = '1.0.2'

# ID used to uniquely identify this module
GUID = '79bd140c-f252-4e22-8675-43be3f934c48'

# Author of this module
Author = 'Patrick Fieldson'

# Company or vendor of this module
CompanyName = 'N/A'

# Copyright statement for this module
Copyright = '(c) 2023 Patrick Fieldson. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Manager module to get and set Windows display settings. Supports resolution, enablement, HDR, and more.'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '5.1'

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @(
    'PSFramework'
)

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
ScriptsToProcess = @(
    # Automatically import required data structures and formats to the caller's scope
    # Powershell classes are not loaded by Import-Module so we use a script to load them via other means instead of a module. 
    # This all means we have to also expose module internal interop classes to the caller, but there is no other option with how powershell classes work.
    '.\lib\Import.ps1',
    '.\structures\Import.ps1'
)

# Type files (.ps1xml) to be loaded when importing this module
TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @(
    'GetAllPotentialDisplays',
    'GetEnabledDisplays',
    'GetPrimaryDisplay',
    'GetDisplayByMonitorName',
    'GetRefreshedDisplay',
    'SetPrimaryDisplay',
    'SaveDisplaysToFile',
    'LoadDisplayStatesFromFile',
    'UpdateDisplaysFromFile',
    'UpdateDisplaysToStates',
    'CurrentDisplaysAreSameAsFile',
    'CurrentDisplaysAreSameAsStates'
)

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# List of all modules packaged with this module. For documentation/reference only
ModuleList = @()

# List of all files packaged with this module. For documentation/reference only
FileList = @(
    './LICENSE',
    './structures/Display/Display.psm1',
    './structures/Display/DisplayFormats.ps1xml',
    './structures/Display/DisplayTypes.ps1xml',
    './structures/Import.ps1',
    './lib/Win32Interop/DisplayConfig.cs',
    './lib/Win32Interop/DisplayDevices.cs',
    './lib/Win32Interop/DisplaySettings.cs',
    './lib/Win32Interop/Win32Errors.cs',
    './WindowsDisplayManager.psd1',
    './WindowsDisplayManager.psm1'
)

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{
    PSData = @{
        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @(
            'Graphics',
            'Display',
            'Monitors'
        )

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/patrick-theprogrammer/WindowsDisplayManager/blob/main/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/patrick-theprogrammer/WindowsDisplayManager'

        # A URL to an icon representing this module.
        IconUri = 'https://github.com/patrick-theprogrammer/WindowsDisplayManager/blob/main/assets/logo.png?raw=true'

        # ReleaseNotes of this module
        # ReleaseNotes = ''
    }
}

# HelpInfo URI of this module
# TODO add developer API documentation for this module
# HelpInfoURI = ''
}
